### ISSUE TITLE
Possible compatibility issue with better rolls

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/enhancedcombathud#100]
I'm getting this error with betterrollsfor5e 1.7.0 and Argon 1.1.6.

```
foundry.js:8850 Uncaught (in promise) Error: You must provide an _id for every object in the update data Array.
[No packages detected]
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:8850)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8824)
    at ClientDatabaseBackend.update (backend.mjs:153)
    at async Function.updateDocuments (document.mjs:366)
```

It happens when you click any of the basic actions (dodge, shove, etc.).

I saw there was a conversation about it here:
https://discord.com/channels/844900867240361984/868966998816739378/872520032163364944

But I'm not sure if it is the same? Does BR need to be patched again or is it something on your end?
Adding ` && item.data?.data?.recharge?.charged` to line 1271 in custom-roll.js fixed it, but not sure if it breaks something else.

**Comment by theripper93** [comment]
This is an issue on br end I’m pretty sure, would you mind opening the issue on their repo, noting I can do on my end
