### ISSUE TITLE
Flashing Text Window

### ISSUE THREAD

**Issue by Fridan99** [theripper93/enhancedcombathud#101]
Apparently a floating text window flickers when there are top lines. Now i test the bug with all modules disable, and the bug persist. 

**ALL OTHER MODULES DISABLED?** (true)
**Module:** (Argon hud 1.1.6, and its dependencies lib-color Setting 2.8.1, libWrapper a.11.0.1)
**Conflicting Module (NO)**: 
**Foundry and System version**: Foundry 0.8.9, DnD5e 1.5.5
**OS, Hosting, Browser (Foundry app itself "hosting")**:
**Short Description of bug**: flashing window description text above lines
**Simple steps to reproduce the bug**: create a test world, install Argon Hud, its dependecies, and create an actor with more than 3 cantrips. 
**Screenshots and/or console errors**:

Img (No console error)
![6](https://user-images.githubusercontent.com/86131373/146659775-d5fcb575-e710-467b-a564-4654326278d7.jpg)

Video
https://user-images.githubusercontent.com/86131373/146659785-c9ff5495-0912-46ae-a5b6-3498e30187a2.mp4

**Comment by theripper93** [comment]
ahhh, ye i know what's going on, that will happen if the screen resolution is small or tooltips are too big, reduce the tooltip scale and the issue will go away

**Comment by Fridan99** [comment]
I have reduced the tooltip scale to 0.1 (which is very small) and the bug persists. 

Hud Scale 0.5 and tooltip scale 0.8 (then reduce the tooltip to 0.7 and so on to 0.1)

**Comment by theripper93** [comment]
screen resolution?

**Comment by Fridan99** [comment]
> I have reduced the tooltip scale to 0.1 (which is very small) and the bug persists.
> 
> Hud Scale 0.5 and tooltip scale 0.8 (then reduce the tooltip to 0.7 and so on to 0.1)

1920x1080

**Comment by Fridan99** [comment]
I don't know if the configuration I have of the Argon.... itself is of any help, but just in case I'll send you a screenshot. 
![6](https://user-images.githubusercontent.com/86131373/146660351-c8cf01af-e37f-45b9-b5b6-b216795f0d5d.jpg)
![7](https://user-images.githubusercontent.com/86131373/146660357-5b95a300-0819-4db8-ab03-902baa3db9cf.jpg)

**Comment by theripper93** [comment]
fixed in 1.1.7
