### ISSUE TITLE
[Feature Request] Pathfinder 2 implementation

### ISSUE THREAD

**Issue by altair984** [theripper93/enhancedcombathud#102]
Hi, thank you very much for your module, I think it's great. I would just like to know if there is a way to do the same but for pathfinder 2. thank you very much for your work and your time!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
