### ISSUE TITLE
Action Tracker auto-refreshes everything if you switch tokens

### ISSUE THREAD

**Issue by GambetTV** [theripper93/enhancedcombathud#105]
Not sure if this is intentional or not, but the action tracker is useless for the DM if it is intentional, and it's useless for players if they control more than one token on the map. If you switch tokens on the HUD, it automatically refreshes the action tracker. This makes tracking reactions, for instance, basically impossible for the DM.

**Comment by theripper93** [comment]
the action tracker is not saved on the token, switching or closing\reopening it will reset it - this is intentional.
