### ISSUE TITLE
Hud not working for 1 user who is outside my local network...using internet.

### ISSUE THREAD

**Issue by jodycummings** [theripper93/enhancedcombathud#106]
Other users are all within my network and they can use the hud perfectly...

Any ideas why the one person outside my local network could not use it?

Thank you the hud is freaking amazing!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
