### ISSUE TITLE
System Availability 

### ISSUE THREAD

**Issue by keyxmakerx** [theripper93/enhancedcombathud#109]
I know i'm breaking protocol just posting a question here, apologies. 

But can this module work with other systems. My players loved it, but we recently switched to Advanced 5e by Levelup, and I can't seem to even see it in the Manage Modules anymore. Since my players are pushing for it, I thought i'd reach out to see if it was a system agnostic to only 5e. And if so, could it be given supported for a5e in the future? 

Again, awesome module!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
