### ISSUE TITLE
[Bug] Equipped (or any) Weapons not showing in Argon Hud by default

### ISSUE THREAD

**Issue by JavaShipped** [theripper93/enhancedcombathud#111]
### The Issue
(Edited with bug information template)

**ALL OTHER MODULES DISABLED?** (true)
**Module:** ArgonHUD 1.2.4
**Conflicting Module (if applicable)**: N/A 
**Foundry and System version**: eg. Foundry v9(255) DnD5e 1.5.7
**OS, Hosting, Browser (if applicable)**: Ubuntu - Hosted (Oracle), (My PC) Windows 10 - Firefox (97.0.2 (64-bit))
**Short Description of bug**: 
I have been setting up a brand new campaign and wanted to use your HUD, it looks sweet as hell. But on using it for the first time, I noticed that I can't see my PC weapons in the Argon HUD, but I can see NPC's weapons.

In my main world I have a BUNCH of modules active, but I've tested this one my testing/dev world too.

**Simple steps to reproduce the bug**: 

- Any character placed on canvas (I used custom PC's but also reproduced with the foundry starter characters)
- Load Argon (default configuration)
- See weapons aren't visible.
- Load NPC with weapon equiped
- See Weapon Equiped.

**Screenshots and/or console errors**: See Below

### Modules active: 

- Betterrollsfor5e, 
- Earnies Modern UI. 

### Troubleshooting already taken
I don't know what I could do other than
- update all modules
- reset browser cache
- Uninstall/Reinstall Argon HUD
- Force Update for Foundry

### PC **not** showing equiped weapons in Argon Hud
![image](https://user-images.githubusercontent.com/29931954/157340718-cb616fa1-01dd-447b-9a2a-2d7ae11c2409.png)

### NPC **Showing** Equipped weapons 
![image](https://user-images.githubusercontent.com/29931954/157341411-a9bf027b-4197-4ce2-b263-aaa5ade7c228.png)

### Showing the issue with ONLY Argon HUD enabled
![image](https://user-images.githubusercontent.com/29931954/157342174-222345be-ea9c-4629-ac7e-7b4b6d3289e1.png)

### Additional Information: 

- The weapons show up as intended for PC's when you select "show weapons in use item section". 

![image](https://user-images.githubusercontent.com/29931954/157341662-3be96992-6608-4832-b2d1-5337ae75b34e.png)

Spells work absolutely fine and integrate with other modules like combat utility belt. Same with NPC weapons. Just not PC weapons.

**Comment by theripper93** [comment]
This is intentional, weapons are automatically generated for npcs but are kept to manual for PCs

**Comment by JavaShipped** [comment]
Ah okay, so Argon doesn't show any weapons as an main action or bonus action in the hud, the player has to use the "use item" or their character sheet? If so I'll relay that to my players, we were just a little confused! Cheers for the reply.

**Comment by theripper93** [comment]
No , you add it to the sets, then select the set
