### ISSUE TITLE
Moving the Argon's token HUD button to the right

### ISSUE THREAD

**Issue by TergusI** [theripper93/enhancedcombathud#113]
Just a small suggestion for improvement: could you add the option to move Argon's token HUD button to the right column of the token HUD?

Thanks!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
