### ISSUE TITLE
Player image displays differently on Firefox and Safari than Chrome/Chromium

### ISSUE THREAD

**Issue by Spectre-63** [theripper93/enhancedcombathud#115]
Hi all - 

ran into an oddity while testing tonight and wanted to bring it up, although I'm unsure how many would be affected: the player character image appears greyed out when using the HUD in Firefox or Safari than it does from within Chrome or Chromium browsers:

Chromium:
![image](https://user-images.githubusercontent.com/65740836/170852924-8cf724df-dcf3-4e3d-99b8-8b4be5cdd35d.png)

Firefox:
![image](https://user-images.githubusercontent.com/65740836/170853071-f6b006fe-d2c1-4c50-b8c4-a462a75ab479.png)

Similar issue to Firefox in Safari - please advise if I can provide further detail.

**Comment by theripper93** [comment]
I’m aware, but as the repo says, argon was made for chrome, other browsers don’t handle advanced css well, can’t do much about it
