### ISSUE TITLE
Text on icons is unclear at <1 scale.

### ISSUE THREAD

**Issue by LtDerek** [theripper93/enhancedcombathud#118]
Would it be possible for the text to change font size rather than simply scaling down image of the orginal text? 

I think that would make it seem more crisp.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
