### ISSUE TITLE
Shove action

### ISSUE THREAD

**Issue by simtudor** [theripper93/enhancedcombathud#119]
Great Module, I like the design a lot. I think the Shove action should be labeled "Grapple / Shove" or add a new button for Grapple and even the interface out by also adding the Help Action.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
