### ISSUE TITLE
Suggestion: Movement Hider / Compatability

### ISSUE THREAD

**Issue by ProStashio** [theripper93/enhancedcombathud#120]
A module I have been using a lot is 'Terrain Ruler', it makes battle maps with difficult terrain much easier to use. I would love it if either the movement of the HUD either worked with this or was able to be hidden to use it with a mod that is compatible.

Bonus suggestion: With the above, I also use the 'Reset Movement' module if players want to change their minds. It would be great if this was possible with the hud or if compatibility could be introduced. As of right now, you have to close and reopen the hud to reset the movement.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
