### ISSUE TITLE
Suggestion: Ammo Swapper

### ISSUE THREAD

**Issue by ProStashio** [theripper93/enhancedcombathud#121]
I have a Ranger that finds the going in to edit what ammo they are using kind of awkward. Having an ammo swapper that could be done easily in the HUD would be a massive boon!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
