### ISSUE TITLE
k is not defined

### ISSUE THREAD

**Issue by flynnkd** [theripper93/enhancedcombathud#123]
Error message 'k is not defined' is showing up during update.  Reinstall has same issue.  
DnD 1.6.3.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
