### ISSUE TITLE
Text blurred when HUD scaled down

### ISSUE THREAD

**Issue by jmorim** [theripper93/enhancedcombathud#124]
**ALL OTHER MODULES DISABLED?** (true)
**Module:** (Argon - Combat HUD v1.3.2)
**Conflicting Module (if applicable)**: NA
**Foundry and System version**: Version 9 B 269, DnD5e 1.6.3
**OS, Hosting, Browser (if applicable)**: Windows 10, Self hosted on Arch, Chrome
**Short Description of bug**: Scaling the HUD below 1 results in blurred text
**Simple steps to reproduce the bug**: Open module settings and decrease the scale slider
**Screenshots and/or console errors**:
Scale = 1
![image](https://user-images.githubusercontent.com/34515725/179339159-b9ad5acb-9c14-4938-a839-da4c74e1c4e7.png)
Scale = 0.5
![image](https://user-images.githubusercontent.com/34515725/179339161-26c5ff14-aad7-485b-b37e-f47753c23b25.png)

**Comment by theripper93** [comment]
This is due to the nested css scalding used in argon , there is no fix to the issue outside than remaking the module from scratch, so I’m afraid this is a wontfix

**Comment by jmorim** [comment]
That's ridiculous.
