### ISSUE TITLE
HUD default size doesn't take screen dimensions into account

### ISSUE THREAD

**Issue by haqa** [theripper93/enhancedcombathud#125]
For most characters the default sizing of HUD is too big for a 1080p screen.

Would it be possible for it to detect the screen (not window) dimesions and scale itself automatically to fit (Taking into account if the right panel is open or closed)? Perhaps have the manual sizing as an override, but not the default?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
