### ISSUE TITLE
Cast Spell is showing all Spells not just the prepared spells

### ISSUE THREAD

**Issue by CasualTerror** [theripper93/enhancedcombathud#126]
Title. When I or my player click on cast spell it shows all the spells, not just the ones prepared. The list is a little long for clerics.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.

Also, check module settings
