### ISSUE TITLE
[Bug] Cast Spell is showing all Spells not just the prepared spells

### ISSUE THREAD

**Issue by CasualTerror** [theripper93/enhancedcombathud#127]
**ALL OTHER MODULES DISABLED?** True
**Module:** (name and version) Argon - Combat HUD ver 1.3.2
**Foundry and System version**: Foundry v9 Build 269   DnD5e 1.6.3
**OS, Hosting, Browser (if applicable)**: Forge hosting, Opera and Chrome Browser
**Short Description of bug**: when clicking cast spell it shows all the known spells not just the ones that are prepared. 
**Simple steps to reproduce the bug**: Have spells in spellbook some not prepared and click on cast spell in the Argon HUD
**Screenshots and/or console errors**:
![Capture](https://user-images.githubusercontent.com/32625656/182375179-37e99548-4f5e-4224-aa1d-f41bb974ff90.PNG)
![Capture1](https://user-images.githubusercontent.com/32625656/182375200-02eb5453-4ab1-45be-97ea-23951ad682e2.PNG)

**Comment by theripper93** [comment]
Please check the module settings.
