### ISSUE TITLE
[Feature Request] Various UI/Ease of Life suggestions

### ISSUE THREAD

**Issue by JasonSlingsCode** [theripper93/enhancedcombathud#129]
As a user, I would like the ability to customize the following:
* The Combat Hud action icons to use my own image files. These customizations would apply both to the HUD and the Active Effects they create.
* The default font which Argon uses.
* Add additional combat actions, for example the `Help` action from D&D 5E which is missing.
* Add additional "weapon slots" for easy access to frequently used items, such as rations and torches.
* Customize the Active Effects of using combat actions. For example, if I click `Hide`, I want to be able to configure an automatic Stealth check in D&D 5E. If I click `Dash`, I want to double my speed.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
