### ISSUE TITLE
Argon Hud causing console errors.

### ISSUE THREAD

**Issue by Zetzaro** [theripper93/enhancedcombathud#131]
When opening the Argon Hud through token button or side buttons, the console gets spammed with a few thousand yellow warnings.
Seems to nearly all be this one: 
![image](https://user-images.githubusercontent.com/112820612/188325806-50d45016-77f6-4b92-9df2-6b85ec321bab.png)

Along with that, hovering over anything in the Argon hud gives a red error:

![image](https://user-images.githubusercontent.com/112820612/188325824-05d0a325-7f84-44e7-a905-df585d530fd2.png)

This is on:
Foundry V10, Build 284. 
DnD 5e 2.0.2.
Argon Hud: 1.4.2

**Comment by theripper93** [comment]
fixed
