### ISSUE TITLE
Feature Request: Moment of Glory!

### ISSUE THREAD

**Issue by Tinhead69** [theripper93/enhancedcombathud#133]
Hi, 

Absolutely love the combat hud, it's just fantastic.

I wondered about the ability to do what I call a 'Moment of Glory'?  similar to critical roles 'how do you want to do this?'

When the npc/creature hit points get to zero or lower, offer a pop up box to the GM to allow the PCs to describe how they kill the creature.  The GM could just close the box if they don't want to do it (and perhaps have a option in the workflow to disable) or it just waits until the GM has closed and then the party know the creature is dead.

Effectively a pause at the moment of death to allow the GM to describe the death or allow the PCs to do so.

Hope this is something you might consider

Anyway, keep up the great work.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
