### ISSUE TITLE
Item Macros aren't recognized

### ISSUE THREAD

**Issue by Ringelrun** [theripper93/enhancedcombathud#134]
Not sure if this is an issue or a feature request but I have quite a few items (spells) that have a small item macro that calls a world script. When using Argon to cast these spells the item macro is either skipped or ignored.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
