### ISSUE TITLE
Target feature not working for players

### ISSUE THREAD

**Issue by Spaxe2** [theripper93/enhancedcombathud#135]
when my players try to attack with the combat hud the target selection does not work for them but as the gm its work for me

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
