### ISSUE TITLE
[Request] Hide Expended Spells and Features

### ISSUE THREAD

**Issue by LonePaladin** [theripper93/enhancedcombathud#148]
Some characters have abilities that can only be used a limited number of times in a day or encounter; in some rulesets (like PF2), some spellcasters have to prepare spells ahead of time, with expended spells no longer being available. Currently, the Argon module still displays features that have been used up, just with the images grayed out. This can create a lot of visual clutter, requiring the user to closely examine an icon to see if it is in color or not.

It would be helpful to have a setting that would hide any abilities that have a limit on usage and have been expended.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
