### ISSUE TITLE
Bug: Switching weapon set doesn't update character stats in hud

### ISSUE THREAD

**Issue by YuanRamirez** [theripper93/enhancedcombathud#31]
When switching weapon sets, changes to the character's stats are not reflected in the hud. The most simple example of this would be switching from a set with shield to one without a shield or vice versa.
The changes are only shown when you deactivate the hud and enable it again (or if the hud gets updated for other reasons such as updates to HP).
The same is also true for items with active effects that change the characters stats (+1 to AC or +1 to spell save DC for example).

Shield equipped:
![enhancedCombatBugAC](https://user-images.githubusercontent.com/24588007/128840893-216fdb74-73a4-4352-9645-0660cfc66f99.jpg)
Shield unequipped:
![enhancedCombatBugAC2](https://user-images.githubusercontent.com/24588007/128840959-10f90aa0-246f-4642-bfad-ef250d84f48c.jpg)

**Comment by theripper93** [comment]
While changes if stats are not reflected. The ac and how should be updated (and was working) I will investigate

**Comment by theripper93** [comment]
Ac should be fixed
