### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Wokeye27** [theripper93/enhancedcombathud#33]
theripper93, you;ve smashed it again! Love it. 

Some suggestions from me, with the aim of helping new players as I think this is especially helpful for that:
1) it would be great if both 'roll initiative' and 'open character sheet' buttons had tooltips or labels. 
2) Movement tracker: would it be possible to make this optional, and also convert it to feet rather than multiples of 5' (eg 30' instead of '6')?  Maybe changing the label to a foot or boots instead of box might make this more intuitive too.
3) I noticed bonus action item features do not come up (eg boots of speed activation) - could the 'use feature' include items eg  'use bonus action feature or item'? 
4) tracking consumables eg ki points would be sensational, maybe over the image.  
5) The char name and class comes up right where a bunch of images might have the head.  Having an option to move this to the bottom of the image above the HP, AC etc  would be ace. 
![image](https://user-images.githubusercontent.com/77101610/128869286-af55c9a9-3c29-4a41-a29b-67152c4afd3b.png)
6) it might be unclear to new players why a weapon attack is shown in the reaction menu.  I'm wondering if a label 'opportunity attack' might possibly help here if that is what is intended.  A tooltip for this mechanic would be awesome.

Grain of salt, of course! Keep up the great work.  Cheers Wok

**Comment by theripper93** [comment]
1. Ye that makes sense
2. Not really, we do not have plans to change that. also it does not show multiple of 5 but squares of movement (so if you have a 10ft grid it would be different)
3. We don't have enough space to include everything, we are not sure if there is a solution, if we find a clean one we will think about it
4. That's traked in the item. if you have a Ki feature with uses (how it's usually set up) it will show. Having it on the portrait is unreasonable as i would require per class special coding
5. Most portrait images have spacing on top yours just happens to have 0 spacing for some reason, just edit the image
6. That seems clear enough to me, and and explanation by  the dm would be pretty quick and painless. The HUD assumes that the player knows at least the most basic rules

**Comment by Brimcon** [comment]
I am in agreement that having the Name/Class/Subclass thing be an option to be moved down to the bottom.

![image](https://user-images.githubusercontent.com/7198283/128896416-f8621ea6-52ff-46fa-9687-2d4ced1ab94d.png)

A lot of portraits and Character Art are custom made either through HeroForge or drawn by players themselves and tend to have the head at the top. Having the option would be nice regardless.
