### ISSUE TITLE
Ammo update

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/enhancedcombathud#36]
It would be nice if the ammo spent get's updated after a roll that spends ammo.

Right now the ammo updates if you click it again.

**Comment by theripper93** [comment]
it's kind of an issue of how items are updated. It's kind of a mess updating the ammo properly. Can you explain exactly the step to reproduce this?

**Comment by Ikabodo** [comment]
I think I realised something.

It seems to be working when I'm using a crossbow, but now a dagger I think this is because I use a macro to update the ammo count.

I have no expectations for you to fix such edge cases. :) But it would be nice to know if there is a special kind of update that is required for the bar to update properly.

**Comment by theripper93** [comment]
ye not gonna fix that kind of edge case, i think if you switch sets it will refresh the count
