### ISSUE TITLE
open up to systems other than D&D 5e through end-user customization?

### ISSUE THREAD

**Issue by EsotericOdyssey** [theripper93/enhancedcombathud#37]
I know it says in the FAQ that Argon is "hardcoded for dnd5e", but is this because it's impossible for you to set it up any differently, or just because you'd rather not commit to creating a custom implementation of the module for every foundry system? If it's the latter, would it be possible to just allow users to configure the module's various functions and HUD elements for whatever system they're using themselves? Like, set custom attribute or item paths to define how to track movement and actions and spells/abilities?

**Comment by theripper93** [comment]
nope, the only way to make it work is to make a fork and edit the code, the amount of settings necessary to achieve that would be completely insane
