### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by akrigline** [theripper93/enhancedcombathud#41]
The readme includes this line:

> Q: Can you add compatibility for X system? > A: No, Argon is hardcoded for dnd5e. If you want you can make a fork for a specific system. You have to include the licence section and credit the original authors (theripper93, Mouse0270) and include links to our patreon page\website (if provided). While you are free to fork this project it must remain free and you cannot profit out of it.

I wanted to ask what particular limitations you are putting on the code in this project. I don't see any License file or annotation except regarding the imagery, which makes me hesitant to fork this project as I am not sure what parts I would be allowed to use in another application.

Applying an [established open source license](https://choosealicense.com/) to this project would clarify what rights a developer who forks this project has and what limitations you are putting in place.

**Comment by theripper93** [comment]
I did forget, license added
