### ISSUE TITLE
Feature suggestion: temp HP e temp Max HP

### ISSUE THREAD

**Issue by Gieff** [theripper93/enhancedcombathud#44]
First of all, *Iove* the module.

The interface lacks a quick way to tell if there are temporary hit points, or temporary maximum hit points. 
Quick mock ups to render the idea:

temp HP
![temphp](https://user-images.githubusercontent.com/84387556/128997840-10391f6c-28e4-4cd8-b076-573270bb3e75.png)

temp Max HP
![maxhp](https://user-images.githubusercontent.com/84387556/128997907-da9b199b-4c91-49b6-9afe-94724d353b87.png)

Other things that i noticed: missing localization strings for AC, HP, Spell DC

**Comment by theripper93** [comment]
will be added in the next update
