### ISSUE TITLE
Player hotbar not disappearing

### ISSUE THREAD

**Issue by thedigitaldungeonmaster** [theripper93/enhancedcombathud#46]
I host the game on moltenhosting. When I'm logged in as a GM, everything works perfect. I open the HUD and the player configuration, macro button, and hotbar buttons all disappear and are replaced by the HUD. When I log in as a player, all the elements disappear except for the hotbar. It stays behind the HUD kind of peeking out the bottom. 

I tested this on multiple browsers (Chrome, Edge, Firefox, Opera) and all had the same issue. I shutdown all my other modules, and the problem persisted. 

FYI - this is a GREAT module.

**Comment by theripper93** [comment]
this seems to be a very isolated issue that i cannot reproduce. If it comes up again and someone else manages to isolate it i'll have it fixed
