### ISSUE TITLE
Features slots

### ISSUE THREAD

**Issue by rbl047** [theripper93/enhancedcombathud#49]
Hello. I'd like to help to improve the module with ideas. 
I miss a slot that shows "features". Would be awesome to have that.
![Screenshot_1](https://user-images.githubusercontent.com/46825122/129087999-007c626d-3097-4ef7-9aae-c6eaf8049ca0.png)

**Comment by theripper93** [comment]
ehm... there is, they don't show because they don't have a use of action\bonus\reaction

**Comment by rbl047** [comment]
> ehm... there is, they don't show because they don't have a use of action\bonus\reaction

I see! But wouldn't be nicer it to appear even not having only "action\bonus\reaction" ?

**Comment by theripper93** [comment]
no, because it's a combat hud....

**Comment by rbl047** [comment]
> no, because it's a combat hud....

Some features are made for combat. Sometimes a player could forget to use it. If I need to check multiple Character Sheet every time to see if there is some important feature to be used in combat, the Argo HUD lose some of its strength.  
PS: I loved your work!

**Comment by theripper93** [comment]
sure but the reality is there is not enough space for everything, if we figure something out then maybe

**Comment by rbl047** [comment]
> sure but the reality is there is not enough space for everything, if we figure something out then maybe

Nice! Thanks :)
If somehow could be possible to do that, I would be grateful =D
![image](https://user-images.githubusercontent.com/46825122/129092068-ccf32d69-e22c-49b5-9caf-ab1c3c48d593.png)
