### ISSUE TITLE
Shield is displayed as a bonus action

### ISSUE THREAD

**Issue by TPNils** [theripper93/enhancedcombathud#50]
Title says most of it. The shield does not have an action associated with it but it is displayed as one

![image](https://user-images.githubusercontent.com/6439997/129096774-999cf0d0-bad1-48b6-aa22-1c86f98523f5.png)

**Comment by theripper93** [comment]
ye, that's just how sets are designed. since it's left hand right hand, but it also allows for custom items in case they are not included in the hud filters

**Comment by TPNils** [comment]
Thats quite a fast response!

To me it would seem logical to exclude any item that has no activation type (= empty not the "none" action type, i think that should be shown for free actions maybe?) and no action(/damage) type.

I cant quite think of something to show when it meets both of those parameters. It would cover normal shields and spell focuses.

**Comment by theripper93** [comment]
ye that makes sense, gonna be in the next update
