### ISSUE TITLE
Suggestion: Movement Section- "fa-cube" change to "fa-running"

### ISSUE THREAD

**Issue by buttonpushertv** [theripper93/enhancedcombathud#51]
This is really a great module. I love the concept! Great execution!!

It was not immediately apparent that the movement section was pertaining to movement. At first glance, I thought it was some sort of resource tracker. To make it stand out as movement, maybe consider changing the "fa-cube" to "fa-running"?
![screenshot 1628713761](https://user-images.githubusercontent.com/24526709/129099345-5c6bb9fa-18b9-4794-bf73-f1225ac34b0b.png)

**Comment by theripper93** [comment]
it's a cube because it's squares of movement

**Comment by buttonpushertv** [comment]
That makes sense.

Maybe a tooltip that explains what it is? Or maybe that shows distance available to move? The HUD overall was very intuitive except this section.

**Comment by theripper93** [comment]
i'll keep it in mind, for now i'll close the issue, if there are more problem of people not understanding what that is i'll conisder changing it. Thanks for the feedback
