### ISSUE TITLE
Midi QOL advantage/disadvantage doesn´t work for saving throws and abilities check

### ISSUE THREAD

**Issue by FGiorgi** [theripper93/enhancedcombathud#52]
Hi.
First of all: awesome module!
I don´t know if a complete integration with MidiQOL is in the scope of the module but while testing it I noticed that it works wonderfully for everything except for skills and saving throws.

While trying to roll a skill or a saving throw using the hotkeys setup in MidiQOL for advantage/disadvantage from the HUD it rolls them normally, without adv/dis, while for spells, attacks and features the hotkeys work fine. 
Since MidiQOL automates adv/dis, this makes it so it´s impossible to roll skills, abilities and saving throws with adv/dis from the HUD.

**Comment by theripper93** [comment]
known issue, it's beein worked on

**Comment by theripper93** [comment]
issue has been fixed, will be live in next update
