### ISSUE TITLE
Hide weapons in "use item"

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/enhancedcombathud#53]
I think in one of the latest updates weapons started showing up in the use item category. I'm not sure if this is a design choice or not, but I kinda liked the clean look of it before (weapons in sets, and items in items). Stops players from forgetting they only have two hands.

Maybe add a setting to filter out weapons in use items? Just a suggestion.

**Comment by theripper93** [comment]
i'm still playing around on what to include and what not to, i'll wait feedback and decide what to do then
