### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by BadIdeasBureau** [theripper93/enhancedcombathud#57]
The license file in this project states that it's licensed under the GPL.

However, in your readme you also state "You have to include the licence section and credit the original authors (theripper93, Mouse0270) and include links to our patreon page\website (if provided). While you are free to fork this project it must remain free and you cannot profit out of it."

Those are not terms that you can impose in an enforceable way while licensing under GPL - GPL requires credit, and requires that anyone who uses the code also licenses the result under GPL, but has no "non-commercial" restriction (so someone is able to make a profit, provided they also release the new source code under GPL), and the credit required under GPL doesn't include your patreon details.

If the intent is that this should be an alternative license available to those who don't want to relicense their work under GPL, then that's an option available to you- but it should be clearer (and is only available as an option if you're not inheriting the GPL license from some other project).

**Comment by theripper93** [comment]
i guess i'll just remove the no money part
