### ISSUE TITLE
[BUG] the "Don't Autoscale" switched

### ISSUE THREAD

**Issue by PalaNolho** [theripper93/enhancedcombathud#59]
The "Don't autoscale" flag is working the opposite of what the text says.

Right now, if unchecked (which means "scale") the HUD is actually scaling. And when checked (which means "don't scale") its size is fixed.

**Comment by theripper93** [comment]
i think you misuderstood what that does, the hud alway scales, if that is checked it will apply the custom scale ON TOP of the auto calc one
