### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by kisnney** [theripper93/enhancedcombathud#63]
The tooltips are a little disturbing. They are too big (i have found no option to customize its size, which would be nice)  and sometimes appear when I'm trying to select some other option and they get in the way. It would be nice to have an option that makes them appear when I click or right-click the button or something like that.

(Great module, thank you!)

**Comment by theripper93** [comment]
usually that issue is related to screen resolution, what resolution are you on?

**Comment by kisnney** [comment]
1920x1080

But there are players that play with me which use lesser resolutions.

Em qui., 12 de ago. de 2021 às 19:02, theripper93 ***@***.***>
escreveu:

**Comment by theripper93** [comment]
added option to scale tooltips
