### ISSUE TITLE
Enhancement: hotkey support

### ISSUE THREAD

**Issue by SR5060** [theripper93/enhancedcombathud#65]
First just want to say what a great job you did with the UI here, incredibly polished. I would love to be able to completely replace the hotkey bar with this functionality but I know some of my players like to keybind actions; it would be great to support that functionality eventually

**Comment by theripper93** [comment]
that would be a lot of work, it's never gonna happen unfortunatelly. Gald you enjoy Argon!

**Comment by SR5060** [comment]
No worries, just wanted to throw it out there for consideration. Thanks again for the module
