### ISSUE TITLE
Avatar and spell DC being partially covered by movement tracker

### ISSUE THREAD

**Issue by kuchrk24** [theripper93/enhancedcombathud#67]
Foundry 0.8.8
D&D 5e 1.4.2
Argon 0.8.5

![image](https://user-images.githubusercontent.com/74018852/129449392-3d6fec6e-c79a-4007-b9a8-0fd35e0b8ade.png)

**Comment by theripper93** [comment]
If you are not using chrome some elements might not render correctly

**Comment by kuchrk24** [comment]
My browser is chromium based. Tried it on Google Chrome with the same result.

**Comment by theripper93** [comment]
screen resolution?

**Comment by kuchrk24** [comment]
It actually looks ok now. I don't know what changed since this morning because I haven't really been screwing around in foundry after installing this module. If I can figure out what happened I can add more info, but for now I guess it's a non-issue.
