### ISSUE TITLE
Adding ammo auto update

### ISSUE THREAD

**Issue by remiverdel** [theripper93/enhancedcombathud#69]
Hi,

First of all thanks for such an awesome module. Been very useful for my new players.
I have 2 rangers in the team and wanted to suggest adding an auto update to the ammo counter when firing an arrow or bolts. The ammo number is really visible but it's sad that it doesn't update automatically..

Hope it'll arrive one day,

Cheers,
And thanks for all the hard work

**Comment by theripper93** [comment]
the ammos should update, how is your items setup?

**Comment by theripper93** [comment]
identified the cause, fix coming in next update
