### ISSUE TITLE
Not all cantrips show in spell list when "Show only prepared spells" is active.

### ISSUE THREAD

**Issue by iamthe22** [theripper93/enhancedcombathud#70]
When activating the "Only show prepared spells" option, only certain cantrips will show for spell casters.  An example, a druid in my group has only Resistance showing as a cantrip in his spells, though he has Control Flames, Create Bonfire, and Mending chosen as cantrips.  A cleric in my game has none of their cantrips available, and a High Elf ranger does not show his racial cantrip as an available option.

**Comment by iamthe22** [comment]
![image_2021-08-14_235328](https://user-images.githubusercontent.com/88956644/129466502-b904aa55-5b11-447d-ab83-b0860c196337.png)

**Comment by theripper93** [comment]
this is already been fixed, coming into ne next update
