### ISSUE TITLE
Enhancement: Setting to turn off autoequip on load, but keep it on sets

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/enhancedcombathud#73]
The latest update to turn off autoupdate was great! But I suggest an additional option for it. 

Right now the autoequip runs when you select any npc. This causes the combat bar to update several times for the gm and all players when the GM selects a token. Normally not an issues, but causes performance issues i larger battles. Especially combined with other modules.

Since autoequip mainly matters for shields I'd say it's ok to be able to equip when you switch set, but not each time you open a new npc. 

There is a very slight chance that another GM could equip something when you are not there, but I'd say thats very minimal in most cases. 

Just a suggestion!

**Comment by theripper93** [comment]
i don't see this beein an issue, if you have problems with the combat tracker refreshing just disable the auto equip and leave shields on.
