### ISSUE TITLE
[BUG] Attack rolls using incorrect token

### ISSUE THREAD

**Issue by kuchrk24** [theripper93/enhancedcombathud#75]
Foundry 0.8.8
DnD 5e 1.4.2
Argon 0.8.9

I have multiple of the same enemy placed on the map (not linked to actor), with different names. Using the combat hud rolls from the incorrect token (the one that is not selected)

![bug](https://user-images.githubusercontent.com/74018852/129662606-bc454abc-a438-4043-918c-935b57d138ff.gif)

Sorry for the crap quality gif. Had to drop quality a ton to get github to let me upload it. But you can see I have 'Adaptable Cultist Enchanter' selected when I open the HUD and roll a spell. The chat comes up with the other 'Funny' cultists name.

**Comment by theripper93** [comment]
the items are rolled with the dnd5e macro method. Try this: drag the eldritch blast (or whatever) to the macro bar, and try to do the same thing but use the macro bar and not argon, what does it do?

**Comment by kuchrk24** [comment]
Yeah the macro is using the actor.... not the token

**Comment by theripper93** [comment]
yep, it's just intended behaviour, not a bug. (usually the name shown in chat is the actor name, i think you have a module showing the token name)
