### ISSUE TITLE
Spells provided by items are not available

### ISSUE THREAD

**Issue by Mejari** [theripper93/enhancedcombathud#76]
Using modules like [Magic Items](https://foundryvtt.com/packages/magicitems) can allow characters to inherit spells from items and other sources. These spells show up in the character's spellbook tab.

![image](https://user-images.githubusercontent.com/1441727/129787045-34e400a5-419e-4e1d-b811-60811eb83f7c.png)

They don't show up in the "Cast Spell" menu of the HUD. Ideally they'd either show up under the appropriate spell level or, to match the character's spellbook, have a separate "Name of Item" tab that would expand all the spells the item provides like this:

![image](https://user-images.githubusercontent.com/1441727/129787938-bcda8c9f-c106-42cb-a4e2-bde911119abb.png)

and hopefully they'd follow whatever standard flow it uses from the character sheet so it correctly subtracts the charges from the item. Maybe even show charge cost similar to the using of potions, and show the total charges remaining in the place where spell slots are shown?

![image](https://user-images.githubusercontent.com/1441727/129788762-849dbaa2-d68e-4b5c-8d9d-a6dd681f39c3.png)

**Comment by theripper93** [comment]
magic item support is not going to happen

**Comment by Mejari** [comment]
Can I ask why not? It's a pretty popular module and not having the spells there definitely impacts the ability for players to make use of the HUD as their main play-flow. Would it make sense to leave it open as a feature request so if someone who may be interested in implementing it could see?

**Comment by theripper93** [comment]
nope because i'm not accepting pull requests ;)

**Comment by Mejari** [comment]
Well that sucks. Hope you change your mind someday!

**Comment by theripper93** [comment]
nope, got burned by people making pulls and then leaving me to fix them ;) with 20 modules i cannot afford that
