### ISSUE TITLE
Spells under "Cast Spell" showing unprepared spells (inconsistently)

### ISSUE THREAD

**Issue by Mejari** [theripper93/enhancedcombathud#77]
Very strange one. When I am logged in to the Foundry client, either as a GM or as the player, only their prepared spells show up under the Cast Spell menu option, as expected. However, when I am logged in via a browser (chrome), either as a GM or as the player, or when the player is logged in on their own device via the browser, all of their spells for that level show up, regardless of if they are prepared or not.

![image](https://user-images.githubusercontent.com/1441727/129794244-487e0315-8487-4ec4-9495-c0fbe86732eb.png)

(the list on the right is from the player's character sheet with the "prepared" filter selected)

**Comment by theripper93** [comment]
mmm, this is very strange, i wouldn't even know where to look, noone had this problem, are yo using Chrome?

**Comment by Mejari** [comment]
I don't know what my player was using but yes, when reproducing this issue I was using chrome.

**Comment by theripper93** [comment]
i'm assuming no erros in the console and you tested with other mods disabled just in case? i really have no idea how that can happen

**Comment by theripper93** [comment]
also it wasn't reported by anyone else (so i'm assuming it's not a widespread issue)

**Comment by Mejari** [comment]
Correct, no errors in the console. I don't want to risk messing things up by disabling everything in my main world, but exporting the actor seeing the issue into a blank world with only this mod enabled shows the same problem. If I create a new actor and add spells I don't seem to be able to re-create the issue from scratch.

**Comment by theripper93** [comment]
is the actor imported from somewhere?

**Comment by valdier1** [comment]
I also have this same issue, using MS Edge (Chromium) as a cleric. Character is imported from D&D Beyond. No errors in the console over this either

**Comment by theripper93** [comment]
i'm pretty sure the problem lies there, the importer is probably doing something weird with the data

**Comment by theripper93** [comment]
i would suggest to seek information in the dnd beyond importer channels as it does not seem to be a problem with argon iself

**Comment by theripper93** [comment]
i will add that if the authour of the mod knows this to be a known issue and has a workaround for me to implement on my end, tell them to contact me and i'll see it added

**Comment by valdier1** [comment]
Well, it doesn't do this with other things, like tiny sheet or token action
hud? It seems specific to this

**Comment by theripper93** [comment]
Well send over an imported actor that has this problem and I’ll take a look

**Comment by mouse0270** [comment]
@Mejari @valdier1 Can I get a screenshot of this happening... Because I use the importer and signed into Edge, Chrome and Firefox and I did see all the spells, but I didn't have the settings checked. I checked the setting and it filtered to just prepared.

![image](https://user-images.githubusercontent.com/564874/129908524-21743ae0-8c70-4487-8221-dd40cdfb31cc.png)

**Comment by Mejari** [comment]
@mouse0270 I provided a screenshot in the initial report, here is a screenshot of my hud settings:

![image](https://user-images.githubusercontent.com/1441727/129946131-b1c29bbc-d46c-406d-8ec0-fd2b6f298e96.png)

@theripper93 Here's a json character export that shows the issue for me:

[fvtt-Actor-berai-talaviel.zip](https://github.com/theripper93/enhancedcombathud/files/7009144/fvtt-Actor-berai-talaviel.zip)

**Comment by theripper93** [comment]
works withou issue on both our systems, maybe it's a conflict or a broken import

**Comment by valdier1** [comment]
I can't reproduce it today after logging back in. I don't think it's a bad import of the character, because it's the only module it seems to happen in so far? I'm not saying it isn't, but it does seem to be specific.

Screenshots here: 
![image](https://user-images.githubusercontent.com/13425341/129974417-8e4f591f-0cf5-4944-80b9-e35fcec89e8e.png)

[fvtt-Actor-akillas.zip](https://github.com/theripper93/enhancedcombathud/files/7010272/fvtt-Actor-akillas.zip)

**Comment by theripper93** [comment]
gonna be very onest, not able to reproduce, no clue how that happens. if you ever find specific reproduction steps open a new issue
