### ISSUE TITLE
PT-BR language missing in module.json

### ISSUE THREAD

**Issue by renanmgs** [theripper93/enhancedcombathud#80]
I noticed that it has a translation to PT-BR but in the module settings the config is missing, i have to add it manually.
![image](https://user-images.githubusercontent.com/30127127/130086162-38d37dfe-9d21-4fa9-af7b-ef74653e67bb.png)

**Comment by theripper93** [comment]
can you copy paste the json part for ptbr so i don't fuck it up please

**Comment by theripper93** [comment]
fixed

**Comment by renanmgs** [comment]
> can you copy paste the json part for ptbr so i don't fuck it up please

Sorry, i was offline, glad you made it!
