### ISSUE TITLE
Remove active effects

### ISSUE THREAD

**Issue by chrisjbrown** [theripper93/enhancedcombathud#82]
First off, awesome work!!

and more of a question.
Is there an easy way to remove active effects from a character?

example: 
i've clicked hide
click "apply active effects"
Actor gets hide icon
next turn he attacks and is no longer hidden
how can i remove the icon? (without going to character sheet and effects and deleting effect)

**Comment by chrisjbrown** [comment]
I don't see the "Hide" effect in the "assign status effects" menu of the token hud
I can add it with combat utility belt + condition lab
but that just adds/removes a second "Hide" icon

**Comment by chrisjbrown** [comment]
![Capture](https://user-images.githubusercontent.com/1250638/131200445-05d02350-f4e6-427a-97f1-f6fee81bae03.PNG)

**Comment by theripper93** [comment]
ye, not much i can do about it, you could create a custom item called "Hide" with a custom active effect and give it to the actor, that way Argon will use that instead of the default but not sure if it would help much, that's just a limitation of active effects

**Comment by chrisjbrown** [comment]
gotcha. thanks for looking into it.
i'll use the "remove temporary effects" macro for now then 👍
