### ISSUE TITLE
Spells not showing up

### ISSUE THREAD

**Issue by FaeyUmbrea** [theripper93/enhancedcombathud#83]
I have a character in my game with spells from it's subclass (Variant of Arcane Trickster) but they dont show up on the HUD.

**Comment by theripper93** [comment]
did you check your prepared status of the spells?

**Comment by FaeyUmbrea** [comment]
Yeah they're set to "always prepared" so they should show up.

**Comment by theripper93** [comment]
do the spells have use of 1  action or 1 bonus action? only those will show in the hud

**Comment by FaeyUmbrea** [comment]
Ah yeah. Somehow the action setting broke. Thanks for the help!
