### ISSUE TITLE
5E Diagonal Movement Rules are not respected.

### ISSUE THREAD

**Issue by XtraButtery** [theripper93/enhancedcombathud#84]
Foundry Virtual Tabletop: 0.8.9
Argon - Combat HUD: 0.9.1 

Argon - Combat HUD always uses the PHB: Equidistant 5/5/5 method of handling diagonal movement even when DMG: Alternating 5/10/5 movement is selected for the game under system settings. Under this rule every other diagonal is counted as 10 ft rather than 5 ft.

**Comment by theripper93** [comment]
are you moving one square at a time or by dragging?

**Comment by XtraButtery** [comment]
One square at a time using the WASD keys (which is how most of my players move) dragging the entire distance does in fact work correctly however this does not allow breaking up movement in a round.

**Comment by theripper93** [comment]
i'm afraid Argon uses the foundry rouler mesurement to determine the square, there are no custom calculations, so i'm afraid theree is no simple fix for that (basically moving with arrows is the same as doing 1 square drag moves)

**Comment by XtraButtery** [comment]
Unfortunate. I know that [Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler/tree/master) manages to calculate diagonals by creating a persistent ruler throughout the characters turn that is continually modified as more movement is added (although it does not recognise WASD inputs correctly either) would a similar implementation be possible for the future?
