### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by remiverdel** [theripper93/enhancedcombathud#85]
Hi,

I wanted to let you know of an issue I've been having recently. I don't know exactly when that problem started, but there seems to be a scaling issue regarding the movement squares that are hiding the spell DC information. I tried different scale settings and even unchecking the auto resize option and it still keeps hiding that info. Here is a screen shot if you need visual reference.

![Capture d’écran 2021-08-31 à 17 16 21](https://user-images.githubusercontent.com/22896375/131529744-022f613b-fd9e-4f5b-9e3e-4eca76d92372.jpg)

By the way, I don't know if it's the right place to put a feature request. But I thought about maybe adding an option to only hide the macro bar and player list for players that won't use them but keep it for GM so they can see the interface and still use the macro bar for quick macros in combat. Hope it could be a possible feature in the future.

Thanks again for the stunning work,

Cheers,

Remi

**Comment by remiverdel** [comment]
It also seems that when I activate the auto resize option, and reduce the size of the interface, when I click on the little arrow to just keep the save, skill check visible, the size turns down a lot and when I open it back up, it keeps the whole interface way smaller.

**Comment by theripper93** [comment]
i'm aware of the scaling issue with autoscale + minimizing, the other issue is kinda strange, it might be related to the localization that makes the text to big

**Comment by theripper93** [comment]
could you try switching to english to see if the problem persists?

**Comment by remiverdel** [comment]
It might be, I'll try to go back to a french version and see, but I'm pretty sure it wasn't happening a few weeks ago even in French.

**Comment by theripper93** [comment]
i did not do any updates so i don't see what could have changed to be honest

**Comment by remiverdel** [comment]
I deactivated Babele and the french modules. There is still French text here and there, do I need to completely change Foundry's langage in the settings?

**Comment by remiverdel** [comment]
![Capture d’écran 2021-08-31 à 17 30 21](https://user-images.githubusercontent.com/22896375/131531854-28161175-34a0-4036-8f4a-3667301f7440.jpg)

**Comment by theripper93** [comment]
yes please

**Comment by remiverdel** [comment]
Well,

Pretty weird but a server restart fixed my issue even with the localization. I didn’t think of doing it because I host my game on AWS. So, great news!

**Comment by theripper93** [comment]
well, no cluehow that happend, if you ever figure out what it was please reopen the issue with the steps to reproduce

**Comment by remiverdel** [comment]
Sure thing, Thanks for the help
