### ISSUE TITLE
Feature proposition

### ISSUE THREAD

**Issue by remiverdel** [theripper93/enhancedcombathud#88]
Hi man,

Love your module, been using it for the past few weeks, my players love it.
I would love to have an option to disable the macro bar only for players so it removes clutter on their end, but allows the GM to still be able to use quick macros with the keyboard and still seeing the argon interface.

Cheers

**Comment by theripper93** [comment]
Not in my plans, but i'm pretty sure you can fire macros with 1-9 even when the bar is hidden

**Comment by remiverdel** [comment]
Sure thing. Found another module that does just that (Minimal UI).
Thanks
