### ISSUE TITLE
5e version 1.5.2

### ISSUE THREAD

**Issue by Envaris-Avalon** [theripper93/enhancedcombathud#91]
Seems like after upgrading to 5e version 1.5.2 Argon Combat Hud is no longer working?

**Comment by Monsamoai** [comment]
Yeah, the new update for the module has broken the thing. I don't know if it is due to the new dnd5e update or something else, but the HUD won't appear if I press the button or toggle to macro.

**Comment by theripper93** [comment]
The issue should be roesolved, can ether of you confirm?
