### ISSUE TITLE
Problem with using combat hud actions

### ISSUE THREAD

**Issue by Tappinator** [theripper93/enhancedcombathud#94]
Hi
When you use actions added by the combat hud and refresh the page it causes errors that stop the token from being accessible citing "Canvas drawing failed for the TokenLayer, see the console for more details".

The console error looks like this
![image](https://user-images.githubusercontent.com/49347444/143488071-d1fa6617-adeb-42b2-a419-31fc7be802f0.png)

The problem stops if you remove the effect of whatever action you used from the token it's affecting.

Thanks

**Comment by theripper93** [comment]
I cannot seem to reproduce this issue - so it's ether a core foundry bug (as i'm on v9 and cannot test on 0.8.x) or you have a corrupded installation. also try with all other mods disabled and report back

**Comment by Tappinator** [comment]
Did some testing after you said this and yeah, it seems to be an incompatibility with MidiQoL, dunno where specifically though, but it triggers after Midi adds the disengage as an effect. Is there a way I can modify the action you add with the combat HUD?

Thanks

**Comment by theripper93** [comment]
yes, if you create an item in the character sheet with the same name it will use that instead
