### ISSUE TITLE
Auto scaling bug

### ISSUE THREAD

**Issue by Tappinator** [theripper93/enhancedcombathud#95]
Hi,
If you have auto scaling on and repeatedly hide and unhide the HUD it gets progressively smaller.

HUD originally:
![xapuT1uylp](https://user-images.githubusercontent.com/49347444/143488651-114868aa-96cf-42ba-a40a-2cea7b001d80.png)

HUD after hiding and unhiding once:
![firefox_X6wvy9YsDK](https://user-images.githubusercontent.com/49347444/143488675-4c21f434-300b-477c-9bee-9a53c35d706a.png)

HUD after hiding and unhiding twice:
![4hWGsv1GgH](https://user-images.githubusercontent.com/49347444/143488724-07f8e04e-1249-40cf-80c4-327e5ef35a55.png)

Thanks

**Comment by theripper93** [comment]
That is a known issue due to the nested css transform, can't do much about it i'm afraid. You can disable the autoscaling
