### ISSUE TITLE
Suggestion. HUD on selected token (actor)

### ISSUE THREAD

**Issue by Fridan99** [theripper93/enhancedcombathud#97]
I want to make a suggestion, in case you see it as a good option. 

Using the hud, I noticed that when I deselect a token (actor), the hud of the previous token (actor) is still active. 

Let me explain, 

I use the fade out hud at 3 sec. (that avoids that I have to be closing and opening it). 

The problem is that if I deselect the token (actor), the hud remains and if I hover the cursor over the lower part appears .... I think it would be more efficient if it only appears with the selected actor, or at least implement an option to show it with the selected actor. 

I think it would be more efficient to release it when the token is not selected, and give the possibility to completely release the screen. 

Anyway I must tell you that it is an incredible module ..... has surprised me a lot. I can't say anything bad about it.

**Comment by theripper93** [comment]
The hud works that way by desing and it's because otherwise players will have the hud pop in and out in many situations (for example when placing templates to name one) so that's not gonna change i'm afraid - i can se how you would consider it a problem but the hud was mainly designed for players in mind so that's the reasoning behind it

**Comment by Fridan99** [comment]
> The hud works that way by desing and it's because otherwise players will have the hud pop in and out in many situations (for example when placing templates to name one) so that's not gonna change i'm afraid - i can se how you would consider it a problem but the hud was mainly designed for players in mind so that's the reasoning behind it

you're right, I'm looking at it from the GM's position.... xD

**Comment by Fridan99** [comment]
Release the screen in the quickest and most effortless way, it is always a good idea xD

Something similar happens with the Monk's Token Action Hud, it appears when it is needed (in actor selected).

It was just a suggestion xD

**Comment by Fridan99** [comment]
Maybe you can consider in the future some additional option to activate it only in token (actor) selected, instead of changing the hud itself.
