### ISSUE TITLE
Bug with info tool tips getting in the way when you have 3 or more rows of spells

### ISSUE THREAD

**Issue by remiverdel** [theripper93/enhancedcombathud#98]
Hi,

When I use the combat HUD and my character has 3 or more rows of spells the tooltip gets in front of the card and there is absolutely no way to trigger the spell through the HUD. Only workaround is to completely deactivate tooltips which really isn't ideal as my players are fairly new to DnD.

Cheers,

Rémi

**Comment by theripper93** [comment]
you can make tooltips smaller, does that not fix the problem?

**Comment by remiverdel** [comment]
Sadly I have to make them ultra small to be able to click the bottom of the card and then the tooltip is completely unreadable


Rémi Verdel

**Comment by theripper93** [comment]
That tells me that the screen has a ery low resolution, maybe change the zoom level of the browser?

**Comment by theripper93** [comment]
- no followup - closed

**Comment by remiverdel** [comment]
Sorry haven’t seen your answer.
 I have a 4K display and my browser was at 100% zoom level when that happened.
Strangely a few days later it doesn’t happen anymore. It might be due to a scaling issue with the combat HUD as the scale tends to be all over the place on my end, when I switch between different tokens as a GM (tokens who only have a few actions are huge on my screen and others pretty small) or when I collapse the HUD to the bottom left. I’ll try to keep an eye on it if it happens again and try to reproduce it.
Cheers


Rémi Verdel

**Comment by theripper93** [comment]
Check the common/known issues, disabling the autoscale and using a flat scaling will probably solve the issue
