### ISSUE TITLE
Interface suggestions

### ISSUE THREAD

**Issue by Fridan99** [theripper93/enhancedcombathud#99]
Hi! theripper93, the Argon Hud is phenomenal. I would like to make some suggestions to you that I think can optimize or improve the hud a bit. Well it's a personal opinion, the hud is still rated 10 out of 10.

A. Add Show Tooltips for Weapons. I think it is very useful, because if the user wants to save screen space, the weapon information is really irrelevant. Weapons are usually for clicking and roll.... save screen space is ALWAYS positive. 
![2](https://user-images.githubusercontent.com/86131373/145716696-c0217fca-dad1-4f04-8cc6-2ec70625da77.jpg)

One of my players has a problem when accessing the innate and cantrip spells (which are the ones he uses most often). When going to the cantrip tab, which is just below the weapon (quarterstaff), he always finds the text of the weapon, which makes it difficult to access cantrips. If the weapon text could be disabled, it would be very positive. The floating text really gets in the way. The only way to avoid this is to start the cursor above cantrips, but the natural way to access is always below. 
![5](https://user-images.githubusercontent.com/86131373/145720329-1b7a20dd-b9ec-4ab1-bfd0-e2f26f94cf39.jpg)
![6](https://user-images.githubusercontent.com/86131373/145720335-8322ddbe-c12f-47c5-adc6-e7234527bce7.jpg)

B. Add Show Tooltips for Spells. 

C. Possibility to adjust the window scale and text of the displayed information. With this you can adjust correctly to save space on the screen, and leave the screen as clean as possible. Window text that is too large and takes up too much screen real estate is often a hindrance, because it creates conflict when working on the screen. A smaller size offers advantages in terms of not cluttering the screen. 

D. It would be very positive if the information would be automatically hidden by clicking on the skill, spell (and shown again with another hover when you leave the space and select it again)....... It is good that the info is displayed on hover, but I have encountered a slight problem when casting the spell, when I click if the info does not disappear, it hides the subsequent messages and certainly hinders when placing a template. Perhaps by making the info disappear when executing the spell, the screen could be freed to work correctly or maybe if the position of the message could be configured, example on the sides instead of in the central area of the screen, this would reduce conflicts when working in the central area and with the hud. 

Probably if the position of the info window could be configured, I would put it over here. I free the central work area to work with tokens, templates,..... (and configurable in size, as a very large size could get in the way). Probably if it could be placed on the sides, it should have some option of how long the information remains once you stop hovering on the skill, since if you want to go to that window to navigate up/down, the window would disappear immediately when you finish the hovering on the skill or maybe another option is that while the informative text is displayed on the screen, the option to zoom the screen with the mouse wheel would be blocked, and that mouse wheel just serves to scroll down or up the text instead of zooming the screen while the text is displayed (I don't know if this could be done or not). 
![6](https://user-images.githubusercontent.com/86131373/145722058-42d161b1-e2c7-4273-839c-58f6b69bc443.jpg)

In this image you can see how it interferes with a concentration message, and later when you have to place the template. Leaving the screen as clean as possible is always positive when working with skills.
![4](https://user-images.githubusercontent.com/86131373/145717106-70d63a3b-beb8-4b3c-b5f8-16e114b75e48.jpg)

Well, these are some ideas, in case they are useful to you at some point or if you consider them useful.

**Comment by theripper93** [comment]
Hello - it seems you haven’t read this - https://github.com/theripper93/Levels/blob/v9/ISSUES.md as stated in the git page - feature request closed
